version: '3.1'

services:

  certbot-container-staging:
    container_name: 'certbot-staging-container'
    image: certbot/certbot:latest
    volumes:
      - ./letsencrypt-site:/data/letsencrypt
      - ../ProdSetup/certs/etc/letsencrypt:/etc/letsencrypt
      - ../ProdSetup/certs/var/lib/letsencrypt:/var/lib/letsencrypt
      - ../ProdSetup/certs/var/log/letsencrypt:/var/log/letsencrypt
    command: certificates --staging
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge