version: '3.1'

services:

  letsencrypt-nginx-container:
    container_name: 'dhparam_generator'
    image: alpine/openssl
    volumes:
      - ../ProdSetup/dh-param:/apps
    command: dhparam -out /apps/dhparam-2048.pem 2048
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge